# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-20 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20171020_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='otherUsers',
        ),
        migrations.AddField(
            model_name='trip',
            name='users',
            field=models.ManyToManyField(null=True, related_name='attachedtrips', to='crud.User'),
        ),
    ]
