# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-20 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20171020_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='crud.User'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='users',
            field=models.ManyToManyField(related_name='attachedtrips', to='crud.User'),
        ),
    ]
